<div style="width: 100%; clear: both;">
<div style="float: left; width: 50%;">
<img src="http://www.uoc.edu/portal/_resources/common/imatges/marca_UOC/UOC_Masterbrand.jpg", align="left">
</div>
<div style="float: right; width: 50%;">
<p style="margin: 0; padding-top: 22px; text-align:right;">M2.883 · Aprendizaje por refuerzo</p>
<p style="margin: 0; text-align:right;">Máster universitario en Ciencia de datos (<i>Data science</i>)</p>
<p style="margin: 0; text-align:right; padding-button: 100px;">Estudios de Informática, Multimedia y Telecomunicación</p>
</div>
</div>
<div style="width:100%;">&nbsp;</div>


# Módulo 1: ejemplos de Gymnasium

En este _notebook_ cargaremos algunos de los escenarios de Gymnasium y veremos la interacción entre algunos agentes y estos escenarios o entornos.

En primer lugar instalaremos la librería gymnasium (si no la tenemos instalada) .

In [1]:
!pip install gymnasium

Para tener retrocompatibilidad con código creado para OpenAI Gym

In [4]:
import gymnasium as gym

## 1. CartPole
En este primer ejemplo vamos a cargar el entorno CartPole y realizaremos algunas pruebas.

### 1.1. Carga de datos

El siguiente código carga los paquetes necesarios para el ejemplo, crea el entorno mediante el método `make` e imprime por pantalla la dimensión del espacio de acciones (dos acciones: 0 = izquierda y 1 = derecha), del espacio de observaciones (cuatro observaciones: posición del carro, velocidad del carro, ángulo del poste y velocidad del poste en la punta) y el rango de la variable de recompensa (de menos infinito a más infinito).

In [5]:
import numpy as np

env = gym.make('CartPole-v1')
print("Action space is {} ".format(env.action_space))
print("Observation space is {} ".format(env.observation_space))
print("Reward range is {} ".format(env.reward_range))

Action space is Discrete(2) 
Observation space is Box([-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38], [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38], (4,), float32) 
Reward range is (-inf, inf) 


Seguidamente, reseteamos el entorno (acción que hay que realizar siempre después de la creación de éste) e inicializamos las variables que guardarán el número de pasos ejecutados (t), la recompensa acumulada (`total_reward`) y la variable que nos indicará cuándo finaliza un episodio (done).

In [13]:
# Environment reset
obs, info = env.reset()
t, total_reward, done = 0, 0, False

### 1.2. Ejecución de un episodio

A continuación, realizaremos la ejecución de un episodio del entorno CartPole utilizando un agente que selecciona las acciones de forma aleatoria.

El siguiente código realiza la ejecución de un episodio del entorno (este finaliza cuando la variable `done` toma el valor `True`). El agente se implementa mediante el método  `env.action_space.sample()` que selecciona una acción al azar. Se imprime por pantalla para cada paso (_time step_) la observación que genera el entorno (los cuatro valores comentados anteriormente), la acción seleccionada y la recompensa obtenida en ese paso (+ 1 en cada acción hasta que finaliza el episodio).

In [14]:
while not done:
    
    # Render the environment (Doesn't work in Google Colab) 
    #env.render() # --- Uncomment if you want to see the episode
    
    # Get random action (this is the implementation of the agent)
    action = env.action_space.sample()
    
    # Execute action and get response
    new_obs, reward, terminated, truncated, info = env.step(action)
    done = terminated or truncated
    print("Obs: {} -> Action: {} and reward: {}".format(np.round(obs, 3), action, reward))
    
    obs = new_obs
    total_reward += reward
    t += 1
    
total_reward += reward
t += 1
print("Obs: {} -> Action: {} and reward: {}".format(np.round(obs, 3), action, reward))

Obs: [-0.043 -0.041 -0.024 -0.017] -> Action: 1 and reward: 1.0
Obs: [-0.044  0.155 -0.025 -0.317] -> Action: 0 and reward: 1.0
Obs: [-0.041 -0.04  -0.031 -0.032] -> Action: 0 and reward: 1.0
Obs: [-0.042 -0.235 -0.032  0.251] -> Action: 1 and reward: 1.0
Obs: [-0.046 -0.039 -0.027 -0.052] -> Action: 1 and reward: 1.0
Obs: [-0.047  0.156 -0.028 -0.353] -> Action: 0 and reward: 1.0
Obs: [-0.044 -0.039 -0.035 -0.069] -> Action: 0 and reward: 1.0
Obs: [-0.045 -0.233 -0.036  0.212] -> Action: 1 and reward: 1.0
Obs: [-0.05  -0.038 -0.032 -0.091] -> Action: 0 and reward: 1.0
Obs: [-0.05  -0.232 -0.034  0.191] -> Action: 0 and reward: 1.0
Obs: [-0.055 -0.427 -0.03   0.473] -> Action: 1 and reward: 1.0
Obs: [-0.064 -0.231 -0.02   0.171] -> Action: 1 and reward: 1.0
Obs: [-0.068 -0.036 -0.017 -0.128] -> Action: 1 and reward: 1.0
Obs: [-0.069  0.159 -0.02  -0.426] -> Action: 0 and reward: 1.0
Obs: [-0.066 -0.035 -0.028 -0.139] -> Action: 1 and reward: 1.0
Obs: [-0.066  0.16  -0.031 -0.441] -> Ac

Finalmente, imprimimos los resultados y cerramos el entorno.

In [15]:
print("Episode finished after {} timesteps and reward was {} ".format(t, total_reward))
env.close()

Episode finished after 40 timesteps and reward was 40.0 


### 1.3. Simulando varios episodios

El siguiente fragmento de código repite el proceso del apartado anterior para el número de episodios definido en la variable `num_episodes`.

In [16]:
num_episodes = 10

for episode in range(num_episodes):

    # Environment reset
    obs, info = env.reset()
    t, total_reward, done = 0, 0, False
    
    print('Running episode {} '.format(episode+1))
    
    while not done:
    
        # Render the environment (Doesn't work in Google Colab)
        #env.render() # --- Uncomment if you want to see the episode
    
        # Get random action (this is the implementation of the agent)
        action = env.action_space.sample()
    
        # Execute action and get response
        new_obs, reward, terminated, truncated, info = env.step(action)
        done = terminated or truncated
        print("Obs: {} -> Action: {} and reward: {}".format(np.round(obs, 3), action, reward))
    
        obs = new_obs
        total_reward += reward
        t += 1
        
    total_reward += reward
    t += 1
    print("Obs: {} -> Action: {} and reward: {}".format(np.round(obs, 3), action, reward))
    print("Episode {} finished after {} timesteps and reward was {} ".format(episode+1, t, total_reward))
    print('')
    
env.close()

Running episode 1 
Obs: [ 0.025  0.005 -0.004 -0.003] -> Action: 0 and reward: 1.0
Obs: [ 0.025 -0.19  -0.004  0.289] -> Action: 0 and reward: 1.0
Obs: [ 0.021 -0.385  0.002  0.58 ] -> Action: 1 and reward: 1.0
Obs: [ 0.014 -0.19   0.014  0.288] -> Action: 1 and reward: 1.0
Obs: [ 0.01   0.005  0.019 -0.   ] -> Action: 1 and reward: 1.0
Obs: [ 0.01   0.199  0.019 -0.287] -> Action: 1 and reward: 1.0
Obs: [ 0.014  0.394  0.014 -0.573] -> Action: 0 and reward: 1.0
Obs: [ 0.022  0.199  0.002 -0.276] -> Action: 0 and reward: 1.0
Obs: [ 0.026  0.004 -0.003  0.017] -> Action: 1 and reward: 1.0
Obs: [ 0.026  0.199 -0.003 -0.276] -> Action: 1 and reward: 1.0
Obs: [ 0.03   0.394 -0.008 -0.57 ] -> Action: 0 and reward: 1.0
Obs: [ 0.038  0.199 -0.02  -0.28 ] -> Action: 1 and reward: 1.0
Obs: [ 0.042  0.394 -0.025 -0.579] -> Action: 1 and reward: 1.0
Obs: [ 0.05   0.59  -0.037 -0.88 ] -> Action: 1 and reward: 1.0
Obs: [ 0.061  0.786 -0.055 -1.184] -> Action: 1 and reward: 1.0
Obs: [ 0.077  0.981 -

## 2. Frozen Lake
En este segundo ejemplo vamos a cargar el entorno FrozenLake y volveremos a realizar algunas pruebas.

### 2.1. Carga de datos

De la misma forma que en el ejemplo inicial, el siguiente código carga los paquetes necesarios para el ejemplo, crea el entorno mediante el método `make` e imprime por pantalla la dimensión del espacio de acciones (0 = izquierda, 1 = derecha, 2 = abajo y 3 = arriba), el espacio de observaciones (un número del 0 al 15 que indica la posición del agente en el entorno) y el rango de la variable de recompensa (0 para cualquier acción excepto si se llega a la casilla de destino, en cuyo caso la recompensa es 1).

In [39]:
import time

env = gym.make("FrozenLake-v1")
print("Action space is {} ".format(env.action_space))
print("Observation space is {} ".format(env.observation_space))
print("Reward range is {} ".format(env.reward_range))

Action space is Discrete(4) 
Observation space is Discrete(16) 
Reward range is (0, 1) 


Para observar el mapa por defecto (S = casilla de partida, G = casilla de destino, H = agujero, F = casilla con hielo).

In [40]:
print(env.desc)

[[b'S' b'F' b'F' b'F']
 [b'F' b'H' b'F' b'H']
 [b'F' b'F' b'F' b'H']
 [b'H' b'F' b'F' b'G']]


### 2.2. Ejecución de un episodio

A continuación, realizaremos la ejecución de un episodio del entorno FrozenLake utilizando un agente que selecciona las acciones de forma aleatoria.

En el siguiente código inicializamos el entorno, definimos el máximo número de pasos por episodio (`max_steps`) y realizamos la ejecución de un episodio del entorno (este finaliza cuando la variable 'done' toma el valor 'True' o cuando se alcanza el número máximo de pasos estipulado). De nuevo, utilizamos un agente que implementa una política completamente aleatoria (`env.action_space.sample()`). Mediante el método `env.render()` podemos ir viendo la evolución del agente en el entorno desde la casilla de salida S hasta que llega a la casilla de destino G o cae en un agujero H.

In [23]:
# Environment reset
obs, info = env.reset()
t, total_reward, done = 0, 0, False
max_steps = 100

# Render the environment (Doesn't work in Google Colab)
#env.render() # --- Uncomment if you want to see the episode
#print('') # --- Uncomment if you want to see the episode
#time.sleep(0.1) # --- Uncomment if you want to see the episode

while t < max_steps:
    # Get random action (this is the implementation of the agent)
    action = env.action_space.sample()
    
    # Execute action and get response
    obs, reward, terminated, truncated, info = env.step(action)
    done = terminated or truncated
    # Render the environment (Doesn't work in Google Colab)
    #env.render() # --- Uncomment if you want to see the episode
    #print('') # --- Uncomment if you want to see the episode
        
    t += 1
    if done:
        break
    time.sleep(0.1)

print("Episode finished after {} timesteps and reward was {} ".format(t, reward))
env.close()

Episode finished after 16 timesteps and reward was 0.0 


### 2.3. Simulando varios episodios

El siguiente fragmento de código repite el proceso del apartado anterior para el número de episodios definido en la variable `num_episodes`.

In [24]:
num_episodes = 10

for episode in range(num_episodes):

    # Environment reset
    obs, info = env.reset()
    t, done = 0, False
    
    print('Running episode {} '.format(episode+1))

    # Render the environment (Doesn't work in Google Colab)
    #env.render() # --- Uncomment if you want to see the episode
    #print('') # --- Uncomment if you want to see the episode
    #time.sleep(0.1) # --- Uncomment if you want to see the episode

    while t < max_steps:
        # Get random action (this is the implementation of the agent)
        action = env.action_space.sample()
    
        # Execute action and get response
        obs, reward, terminated, truncated, info = env.step(action)
        done = terminated or truncated
        
        # Render the environment (Doesn't work in Google Colab)
        #env.render() # --- Uncomment if you want to see the episode
        #print('') # --- Uncomment if you want to see the episode
       
        t += 1
        if done:
            break
        time.sleep(0.1)
      
    print("Episode {} finished after {} timesteps and reward was {} ".format(episode+1, t, reward))
    print('')

Running episode 1 
Episode 1 finished after 11 timesteps and reward was 0.0 

Running episode 2 
Episode 2 finished after 10 timesteps and reward was 0.0 

Running episode 3 
Episode 3 finished after 6 timesteps and reward was 0.0 

Running episode 4 
Episode 4 finished after 11 timesteps and reward was 0.0 

Running episode 5 
Episode 5 finished after 5 timesteps and reward was 0.0 

Running episode 6 
Episode 6 finished after 5 timesteps and reward was 0.0 

Running episode 7 
Episode 7 finished after 2 timesteps and reward was 0.0 

Running episode 8 
Episode 8 finished after 2 timesteps and reward was 0.0 

Running episode 9 
Episode 9 finished after 7 timesteps and reward was 0.0 

Running episode 10 
Episode 10 finished after 5 timesteps and reward was 0.0 



### 2.4. Calculando la recompensa total de varios episodios

Para medir la eficiencia del agente, podemos calcular la recompensa total de varios episodios. Dado que en cada episodio la recompensa acumulada es 0 si no se llega a la celda de destino y 1 si se consigue el objetivo, medir la recompensa total acumulada de un número de episodios nos da una medida del porcentaje de éxito de nuestro agente.

El siguiente fragmento de código repite el proceso del apartado anterior para el número de episodios definido en la variable `num_episodes` y calcula el porcentaje de acierto del agente. Se omite la renderización del entorno con el objetivo de agilizar la ejecución.

In [26]:
num_episodes = 1000
total_reward = 0

for episode in range(num_episodes):

    # Environment reset
    obs, info = env.reset()
    t, done = 0, False
    
    # Render the environment (Doesn't work in Google Colab)
    #env.render() --- Uncomment if you want to see the path of the agen  

    while t < max_steps:
        # Get random action (this is the implementation of the agent)
        action = env.action_space.sample()
    
        # Execute action and get response
        obs, reward, terminated, truncated, info = env.step(action)
        done = terminated or truncated
        
        # Render the environment (Doesn't work in Google Colab)
        #env.render() --- Uncomment if you want to see the path of the agent
        
        total_reward += reward
        t += 1
        if done:
            break
    
success_rate = total_reward*100/num_episodes
print("{} successes in {} episodes: {} % of success".format(total_reward, num_episodes, success_rate))

12.0 successes in 1000 episodes: 1.2 % of success


### 2.5. Entrenando a un agente

Tal y como hemos podido ver en el apartado anterior, como el agente utilizado elige las acciones al azar, es casi imposible llegar a la casilla de destino G con esta política (el porcentaje de éxito está en un 1 % o 2 %). Vamos a entrenar un agente utilizando el método Q-Learning. Este método (que se estudiará en módulos posteriores) puede implementarse mediante una tabla que va actualizándose a partir de la interacción del agente con el entorno.
El siguiente código implementa este método y realiza el entrenamiento del agente a partir de la ejecución de varios episodios.

__Nota__: recordad que las simulaciones ejecutadas tienen un componente aleatorio y los porcentajes pueden variar de una ejecución a otra.

Empezamos importando algunos paquetes:

In [27]:
import pickle

Inicializamos algunas variables del método que queremos implementar, entre las que se encuentran el número de episodios (`num_episodes`) y el número máximo de pasos por cada episodio (`max_steps`).

In [28]:
epsilon = 0.9
num_episodes = 100000
max_steps = 100

learning_rate = 0.81
gamma = 0.96

Inicializamos a cero todos los valores de la tabla de la función Q (de dieciseis estados por cuatro acciones cada estado), que acabará dándonos una idea de cuál es la mejor acción para cada estado.

In [29]:
Q = np.zeros((env.observation_space.n, env.action_space.n))
print(Q)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


El siguiente código define las funciones que caracterizan al agente (se estudiarán en módulos posteriores de este curso).

In [30]:
def choose_action(state):
    action=0
    if np.random.uniform(0, 1) < epsilon:
        action = env.action_space.sample()
    else:
        action = np.argmax(Q[state, :])
    return action

def learn(state, new_state, reward, action):
    predict = Q[state, action]
    target = reward + gamma * np.max(Q[new_state, :])
    Q[state, action] = Q[state, action] + learning_rate * (target - predict)

El siguiente código realiza tantas partidas del juego como se indican en la variable `num_episodes`. En cada partida (episodio), el agente va interactuando con el entorno y, como fruto de esa interacción, va actualizando los valores de la tabla _Q_. En el código se ha comentado el método `env.render()` con el objetivo de no saturar la pantalla. Así mismo, se imprimen por pantalla aquellos episodios en los que el agente alcanza la casilla de destino.

In [31]:
# Start
for episode in range(num_episodes):
    state, info = env.reset()
    t = 0
    
    while t < max_steps:
        # Render the environment (Doesn't work in Google Colab)
        #env.render() --- Uncomment if you want to see the path of the agent
        action = choose_action(state)  
        state2, reward, terminated, truncated, info = env.step(action)
        done = terminated or truncated  
        learn(state, state2, reward, action)
        state = state2
        t += 1
       
        if done:
            break

    if reward == 1:
        print("Episode {} finished after {} timesteps and reward was {} ".format(episode+1, t, reward)) 

Episode 61 finished after 19 timesteps and reward was 1.0 
Episode 88 finished after 9 timesteps and reward was 1.0 
Episode 137 finished after 9 timesteps and reward was 1.0 
Episode 177 finished after 8 timesteps and reward was 1.0 
Episode 242 finished after 10 timesteps and reward was 1.0 
Episode 326 finished after 13 timesteps and reward was 1.0 
Episode 411 finished after 9 timesteps and reward was 1.0 
Episode 502 finished after 15 timesteps and reward was 1.0 
Episode 577 finished after 9 timesteps and reward was 1.0 
Episode 620 finished after 9 timesteps and reward was 1.0 
Episode 699 finished after 7 timesteps and reward was 1.0 
Episode 719 finished after 14 timesteps and reward was 1.0 
Episode 732 finished after 22 timesteps and reward was 1.0 
Episode 756 finished after 7 timesteps and reward was 1.0 
Episode 822 finished after 15 timesteps and reward was 1.0 
Episode 857 finished after 20 timesteps and reward was 1.0 
Episode 1009 finished after 6 timesteps and reward

Podemos ver los valores finales de la tabla _Q_ después del entrenamiento.

In [32]:
print(Q)

[[0.55207729 0.53524804 0.53007564 0.53116857]
 [0.51337301 0.52541948 0.49083056 0.58278832]
 [0.55556138 0.56355111 0.57044977 0.50331479]
 [0.51077833 0.09131338 0.53983466 0.5746564 ]
 [0.5574925  0.5502434  0.50947766 0.08809338]
 [0.         0.         0.         0.        ]
 [0.66133226 0.01951315 0.12597847 0.00380338]
 [0.         0.         0.         0.        ]
 [0.54567607 0.10826237 0.48382    0.56359677]
 [0.67033293 0.59649328 0.64027378 0.02259283]
 [0.54582023 0.83072329 0.53925394 0.635378  ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.76353994 0.74070653 0.80287173 0.67486135]
 [0.79864488 0.82057806 0.9740117  0.72646789]
 [0.         0.         0.         0.        ]]


### 2.6. Comprobando la mejora
En este último apartado comprobaremos que el agente diseñado consigue mejores prestaciones que el agente aleatorio.

El código es muy parecido al que hemos utilizado mientras entrenábamos al agente, pero se omite la parte de aprendizaje de este. Para ello, simularemos varios episodios utilizando los valores de la tabla _Q_ obtenida en el entrenamiento. Concretamente, el agente selecciona el valor máximo de la tabla _Q_ para cada estado:

In [33]:
def choose_action_max(state):
    action = np.argmax(Q[state, :])
    return action

De nuevo, calculamos la recompensa total de varios episodios y se calcula el porcentaje de acierto que, como puede comprobarse, es superior al del agente aleatorio.

Se ofrece la oportunidad en el código de visualizar (de forma distinta a la vista hasta este momento) los últimos episodios de la simulación (indicados en la variable `num_shows`). Esta opción no está disponible en Google Colab.

In [35]:
from IPython.display import clear_output

num_episodes = 1000
total_reward = 0
num_shows = 5
show_episode = False

# start
for episode in range(num_episodes):

    if (num_episodes - episode) <= num_shows:
        show_episode = False # Set to 'False' in Google Colab
        
    state, info = env.reset()
    
    if show_episode == True:
        print('')
        print('')
        print("*** Episode: ", episode+1)
        print('')
        print('')
        time.sleep(0.8)
        clear_output(wait=True)
        env.render()
    
    t = 0
    while t < 100:
        action = choose_action_max(state)  
        state, reward, terminated, truncated, info = env.step(action)
        done = terminated or truncated  
        
        if show_episode == True:
            time.sleep(0.5)
            clear_output(wait=True)
            env.render()
        if done:
            break

    if show_episode == True:
        time.sleep(0.8)
        clear_output(wait=True)
        print('')
        print('')
        print('Reward = {}'.format(reward))
        print('')
        print('')
        time.sleep(0.8)
        clear_output(wait=True)
    
    total_reward += reward
    
success_rate = total_reward*100/num_episodes
print("{} successes in {} episodes: {} % of success".format(total_reward, num_episodes, success_rate))

197.0 successes in 1000 episodes: 19.7 % of success
